### ISSUE TITLE
Plot UI of Login in Figma

### ISSUE THREAD

**Issue by fayecamilleburi** [fayecamilleburi/DataBytes_ThesesApp#13]

**Comment by fayecamilleburi** [comment]
Components:
[ ] ID Number Field
[ ] Password field
[ ] Validating ID Number with default password as institutional email username

**Comment by AliyahAira** [comment]
Final Design for Log-in:

![Image](https://github.com/user-attachments/assets/3b837565-f31d-4dbd-98a7-1b9e6f2cbb5e)
