### ISSUE TITLE
Plot UI of Main Menu of App in Figma

### ISSUE THREAD

**Issue by fayecamilleburi** [fayecamilleburi/DataBytes_ThesesApp#14]

**Comment by fayecamilleburi** [comment]
Components (For User - Student & Faculty):
- Search Bar Field
- Menu Options Header (Home, Resources, My Profile)
- Recently Accessed = Same functionality as History (Blank if none)
- Under Resources: Dropdown hover = Colleges; Note: Theses files are categorized per college department
- If college department is clicked, theses files will show (Ca be sorted by year and alphabetized)

**Comment by fayecamilleburi** [comment]
Components (For Librarian):
- [ ] Fields for creating, uploading, and modifying theses
- Includes the following:
- [ ] Thesis Title
- [ ] Authors
- [ ] College Program
- [ ] College Department
- [ ] Publish Date

**Comment by fayecamilleburi** [comment]
Components (For Admin):
- [ ] Add, edit, and delete a user
- [ ] Rights will be detected through ID number of user to validate login

**Comment by fayecamilleburi** [comment]
Feel free to add UI components needed!

**Comment by AliyahAira** [comment]
Final Menu UI:
![Image](https://github.com/user-attachments/assets/5f7dca59-b693-4932-8d47-d2c0aef46cc5)
