### ISSUE TITLE
Plot UI of edit name and password for users and librarian.

### ISSUE THREAD

**Issue by fayecamilleburi** [fayecamilleburi/DataBytes_ThesesApp#32]

**Comment by RuselleDaanoy** [comment]
Done ✓

**Comment by RuselleDaanoy** [comment]
![Image](https://github.com/user-attachments/assets/66c68092-45a9-4058-8216-598f0c05bb33)
![Image](https://github.com/user-attachments/assets/d6b4412c-75b1-4bde-a831-8c68cea4951a)
